# Sameer Ramkissoon - CSCI-415 Data Mining
#### Dataset: Algerian Forest Fires
#### Link: https://archive.ics.uci.edu/dataset/547/algerian+forest+fires+dataset

In [14]:
# Reading the Algerian Forest Fires Dataset (right from the link)
import pandas as pd


df = pd.read_csv('data/Algerian_forest_fires_dataset_UPDATE.csv', header=1)
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire

#### Preprocess 1
- Dataset contains TWO tables, each for different region (Bejaia & Sidi-Bel Abbes)
- Using .iloc to split the dataset into its respective parts and set their new index to be the region name
- Combining the separate DataFrames together to make algerian_ff

In [15]:
# Bejaia region index 0:122 in original df
bejaia_df = df.iloc[:122]
bejaia_df['region'] = 'Bejaia'
bejaia_df.set_index('region', inplace=True)

# Sidi-Bel Abbes region index 124:end in original df
sidi_bel_abbes_df = df.iloc[124:]
sidi_bel_abbes_df['region'] = 'Sidi-Bel Abbes'
sidi_bel_abbes_df.set_index('region', inplace=True)

# Combining both parts into algerian_ff
algerian_ff = pd.concat([bejaia_df, sidi_bel_abbes_df], axis=0)

In [16]:
# Viewing the full Bejaia region information
algerian_ff.loc['Bejaia']

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
region,,,,,,,,,,,,,,
Bejaia,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
Bejaia,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
Bejaia,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
Bejaia,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
Bejaia,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Bejaia,26,09,2012,31,54,11,0,82,6,16.3,2.5,6.2,1.7,not fire
Bejaia,27,09,2012,31,66,11,0,85.7,8.3,24.9,4,9,4.1,fire
Bejaia,28,09,2012,32,47,14,0.7,77.5,7.1,8.8,1.8,6.8,0.9,not fire
Bejaia,29,09,2012,26,80,16,1.8,47.4,2.9,7.7,0.3,3,0.1,not fire
Bejaia,30,09,2012,25,78,14,1.4,45,1.9,7.5,0.2,2.4,0.1,not fire

In [17]:
# Viewing the full Sidi-Bel Abbes region information
algerian_ff.loc['Sidi-Bel Abbes']

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
region,,,,,,,,,,,,,,
Sidi-Bel Abbes,01,06,2012,32,71,12,0.7,57.1,2.5,8.2,0.6,2.8,0.2,not fire
Sidi-Bel Abbes,02,06,2012,30,73,13,4,55.7,2.7,7.8,0.6,2.9,0.2,not fire
Sidi-Bel Abbes,03,06,2012,29,80,14,2,48.7,2.2,7.6,0.3,2.6,0.1,not fire
Sidi-Bel Abbes,04,06,2012,30,64,14,0,79.4,5.2,15.4,2.2,5.6,1,not fire
Sidi-Bel Abbes,05,06,2012,32,60,14,0.2,77.1,6,17.6,1.8,6.5,0.9,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sidi-Bel Abbes,26,09,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
Sidi-Bel Abbes,27,09,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
Sidi-Bel Abbes,28,09,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
Sidi-Bel Abbes,29,09,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
Sidi-Bel Abbes,30,09,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [18]:
# Viewing shape of algerian fires Df
print(f"Number of Instances: {algerian_ff.shape[0]}")
print(f"Number of Attributes: {algerian_ff.shape[1]}")

Number of Instances: 244
Number of Attributes: 14

#### Preprocess 2
Focusing on the column formatting of the algerian_ff DataFrame
- CSV showed there was whitespace visible for some column names -> stripping the whitespace away
- CSV also showed there was some whitespace from some fields -> stripping the whitespace away
- Changing the columns to lowercase for readability
- Converting the numerical values to floats (FFMC:FWI are index codes and should not be changed)
- Renaming some columns to include their unit of measurement (Temperature -> temp_c)

In [19]:
# Stripping away the whitespace from the columns & fields
algerian_ff.columns = algerian_ff.columns.str.strip()
algerian_ff = algerian_ff.apply(lambda x: x.str.strip() if x.dtype == "str" else x)

# Changing the column names to lowercase
algerian_ff.columns = algerian_ff.columns.str.lower()

In [20]:
# Viewing data types of all columns -> change Temperature, RH, Ws, and Rain to floats
algerian_ff.dtypes

day            str
month          str
year           str
temperature    str
rh             str
ws             str
rain           str
ffmc           str
dmc            str
dc             str
isi            str
bui            str
fwi            str
classes        str
dtype: object

In [21]:
# Changing temperature, rh, ws, rain to float datatypes
algerian_ff = algerian_ff.astype({
    'temperature': 'float',
    'rh': 'float',
    'ws': 'float',
    'rain': 'float',
})

# Renaming columns with changed datatypes to match the unit of measure + lowercase
algerian_ff.rename({
    'temperature':'temp_c',
    'rh':'rel_humidity_percent',
    'ws':'wind_speed_kmh',
    'rain':'rainfall_mm',
}, axis=1, inplace=True)

# Checking to see if the data types of the columns changed
algerian_ff.dtypes

day                         str
month                       str
year                        str
temp_c                  float64
rel_humidity_percent    float64
wind_speed_kmh          float64
rainfall_mm             float64
ffmc                        str
dmc                         str
dc                          str
isi                         str
bui                         str
fwi                         str
classes                     str
dtype: object

#### Preprocess 3
- Creating a new date column (potentially for line graph analysis) and move to index 0
- Removing any rows containing null class values

In [22]:
# Creating date column to combine day-month-year together
algerian_ff['date'] = pd.to_datetime(algerian_ff[['year', 'month', 'day']])
date_col = algerian_ff.pop('date')
algerian_ff.insert(0, 'date', date_col)

# Checking if column moved properly
algerian_ff.head()

,date,day,month,year,temp_c,rel_humidity_percent,wind_speed_kmh,rainfall_mm,ffmc,dmc,dc,isi,bui,fwi,classes
region,,,,,,,,,,,,,,,
Bejaia,2012-06-01,01,06,2012,29.0,57.0,18.0,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
Bejaia,2012-06-02,02,06,2012,29.0,61.0,13.0,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
Bejaia,2012-06-03,03,06,2012,26.0,82.0,22.0,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
Bejaia,2012-06-04,04,06,2012,25.0,89.0,13.0,2.5,28.6,1.3,6.9,0,1.7,0,not fire
Bejaia,2012-06-05,05,06,2012,27.0,77.0,16.0,0.0,64.8,3,14.2,1.2,3.9,0.5,not fire

In [23]:
# Finding any NA values from Df -> 1 null class meaning we will just remove that row
algerian_ff.isnull().sum()

date                    0
day                     0
month                   0
year                    0
temp_c                  0
rel_humidity_percent    0
wind_speed_kmh          0
rainfall_mm             0
ffmc                    0
dmc                     0
dc                      0
isi                     0
bui                     0
fwi                     0
classes                 1
dtype: int64

In [24]:
# Dropping the row with the NA class value
algerian_ff.dropna(axis=0, subset='classes', inplace=True)

# Verifying if all null values are gone
algerian_ff.isnull().sum() > 0

date                    False
day                     False
month                   False
year                    False
temp_c                  False
rel_humidity_percent    False
wind_speed_kmh          False
rainfall_mm             False
ffmc                    False
dmc                     False
dc                      False
isi                     False
bui                     False
fwi                     False
classes                 False
dtype: bool

### Final Step
Converting newly cleaned algerian_ff to clean CSV in data directory

In [25]:
# One final look through of cleaned dataframe
algerian_ff

,date,day,month,year,temp_c,rel_humidity_percent,wind_speed_kmh,rainfall_mm,ffmc,dmc,dc,isi,bui,fwi,classes
region,,,,,,,,,,,,,,,
Bejaia,2012-06-01,01,06,2012,29.0,57.0,18.0,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
Bejaia,2012-06-02,02,06,2012,29.0,61.0,13.0,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
Bejaia,2012-06-03,03,06,2012,26.0,82.0,22.0,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
Bejaia,2012-06-04,04,06,2012,25.0,89.0,13.0,2.5,28.6,1.3,6.9,0,1.7,0,not fire
Bejaia,2012-06-05,05,06,2012,27.0,77.0,16.0,0.0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sidi-Bel Abbes,2012-09-26,26,09,2012,30.0,65.0,14.0,0.0,85.4,16,44.5,4.5,16.9,6.5,fire
Sidi-Bel Abbes,2012-09-27,27,09,2012,28.0,87.0,15.0,4.4,41.1,6.5,8,0.1,6.2,0,not fire
Sidi-Bel Abbes,2012-09-28,28,09,2012,27.0,87.0,29.0,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
Sidi-Bel Abbes,2012-09-29,29,09,2012,24.0,54.0,18.0,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
Sidi-Bel Abbes,2012-09-30,30,09,2012,24.0,64.0,15.0,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [26]:
# Creating clean CSV from the fixed dataframe
clean_path = 'data/algerian_forest_fires_clean.csv'
algerian_ff.to_csv(clean_path)