Sameer Ramkissoon - Preprocess Dataset

In [18]:
import pandas as pd

df = pd.read_csv('data/Algerian_forest_fires_dataset_UPDATE.csv', header=1)
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire

In [16]:
# Splitting df into two parts (Bejala & Sidi-Bel Abbes Regions)
# Creating new 'region' column for each and setting as index
bejala_df = df.iloc[:122]
bejala_df['region'] = 'Bejala'
bejala_df.set_index('region', inplace=True)

sidi_bel_abbes_df = df.iloc[124:]
sidi_bel_abbes_df['region'] = 'Sidi-Bel Abbes'
sidi_bel_abbes_df.set_index('region', inplace=True)

# Combining both parts into full algerian_forest_fires DataFrame
algerian_forest_fires_df = pd.concat([bejala_df, sidi_bel_abbes_df], axis=0)

In [17]:
# Viewing the Bejala region of the combined df
algerian_forest_fires_df.loc['Bejala']

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
region,,,,,,,,,,,,,,
Bejala,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
Bejala,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
Bejala,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
Bejala,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
Bejala,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Bejala,26,09,2012,31,54,11,0,82,6,16.3,2.5,6.2,1.7,not fire
Bejala,27,09,2012,31,66,11,0,85.7,8.3,24.9,4,9,4.1,fire
Bejala,28,09,2012,32,47,14,0.7,77.5,7.1,8.8,1.8,6.8,0.9,not fire
Bejala,29,09,2012,26,80,16,1.8,47.4,2.9,7.7,0.3,3,0.1,not fire
Bejala,30,09,2012,25,78,14,1.4,45,1.9,7.5,0.2,2.4,0.1,not fire

In [31]:
# Viewing the Sidi-Bel Abbes region of the combined df
algerian_forest_fires_df.loc['Sidi-Bel Abbes']

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
region,,,,,,,,,,,,,,
Sidi-Bel Abbes,01,06,2012,32,71,12,0.7,57.1,2.5,8.2,0.6,2.8,0.2,not fire
Sidi-Bel Abbes,02,06,2012,30,73,13,4,55.7,2.7,7.8,0.6,2.9,0.2,not fire
Sidi-Bel Abbes,03,06,2012,29,80,14,2,48.7,2.2,7.6,0.3,2.6,0.1,not fire
Sidi-Bel Abbes,04,06,2012,30,64,14,0,79.4,5.2,15.4,2.2,5.6,1,not fire
Sidi-Bel Abbes,05,06,2012,32,60,14,0.2,77.1,6,17.6,1.8,6.5,0.9,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sidi-Bel Abbes,26,09,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
Sidi-Bel Abbes,27,09,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
Sidi-Bel Abbes,28,09,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
Sidi-Bel Abbes,29,09,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
Sidi-Bel Abbes,30,09,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [32]:
# Viewing shape of algerian fires Df
print(f"Number of Instances: {algerian_forest_fires_df.shape[0]}")
print(f"Number of Attributes: {algerian_forest_fires_df.shape[1]}")

Number of Instances: 244
Number of Attributes: 14

In [33]:
# Stripping away any whitespace from columns
algerian_forest_fires_df.columns = algerian_forest_fires_df.columns.str.strip()

In [29]:
# Viewing data types of all columns -> change Temperature, RH, Ws, and Rain to floats
print(algerian_forest_fires_df.dtypes)

algerian_forest_fires_df.astype({
    'Temperature': 'float',
    'RH': 'float',
    'Ws': 'float',
    'Rain': 'float',
})

day            str
month          str
year           str
Temperature    str
RH             str
Ws             str
Rain           str
FFMC           str
DMC            str
DC             str
ISI            str
BUI            str
FWI            str
Classes        str
dtype: object

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
region,,,,,,,,,,,,,,
Bejala,01,06,2012,29.0,57.0,18.0,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
Bejala,02,06,2012,29.0,61.0,13.0,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
Bejala,03,06,2012,26.0,82.0,22.0,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
Bejala,04,06,2012,25.0,89.0,13.0,2.5,28.6,1.3,6.9,0,1.7,0,not fire
Bejala,05,06,2012,27.0,77.0,16.0,0.0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sidi-Bel Abbes,26,09,2012,30.0,65.0,14.0,0.0,85.4,16,44.5,4.5,16.9,6.5,fire
Sidi-Bel Abbes,27,09,2012,28.0,87.0,15.0,4.4,41.1,6.5,8,0.1,6.2,0,not fire
Sidi-Bel Abbes,28,09,2012,27.0,87.0,29.0,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
Sidi-Bel Abbes,29,09,2012,24.0,54.0,18.0,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
Sidi-Bel Abbes,30,09,2012,24.0,64.0,15.0,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
region,,,,,,,,,,,,,,
Bejala,01,06,2012,29.0,57.0,18.0,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
Bejala,02,06,2012,29.0,61.0,13.0,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
Bejala,03,06,2012,26.0,82.0,22.0,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
Bejala,04,06,2012,25.0,89.0,13.0,2.5,28.6,1.3,6.9,0,1.7,0,not fire
Bejala,05,06,2012,27.0,77.0,16.0,0.0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sidi-Bel Abbes,26,09,2012,30.0,65.0,14.0,0.0,85.4,16,44.5,4.5,16.9,6.5,fire
Sidi-Bel Abbes,27,09,2012,28.0,87.0,15.0,4.4,41.1,6.5,8,0.1,6.2,0,not fire
Sidi-Bel Abbes,28,09,2012,27.0,87.0,29.0,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
Sidi-Bel Abbes,29,09,2012,24.0,54.0,18.0,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
Sidi-Bel Abbes,30,09,2012,24.0,64.0,15.0,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire